CREATE TABLE `sys_sms` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `to_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收信息人电话',
  `sign_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '短信签名内容',
  `business_id` int DEFAULT NULL COMMENT '业务id',
  `business_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务名称',
  `template_id` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '模板id',
  `param` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '短信正文',
  `timing_flag` int DEFAULT NULL COMMENT '定时发送标识 0否 1是',
  `timing_time` datetime DEFAULT NULL COMMENT '定时发送时间',
  `state` int DEFAULT '0' COMMENT '状态 0未发送 1发送成功 9发送失败',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `exception` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '异常信息',
  `session_context` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'session内容(无需要可忽略)',
  `extend_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '短信码号扩展(可忽略)',
  `sender_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '国内短信无需填写',
  `create_user` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `delete_flag` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;