server:
  port: 8080
  servlet:
    context-path: /server
  address: 0.0.0.0
spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: auth
      datasource:
        auth:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/auth_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: auth_dev
          password: auth_dev
        aili:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/aili_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: aili_dev
          password: aili_dev
        chinaybop:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/chinaybop_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: chinaybop_dev
          password: chinaybop_dev
        king:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/king_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: king_dev
          password: king_dev
        proxy:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/proxy_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: proxy_dev
          password: proxy_dev
        xpxl:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/xpxl_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: xpxl_dev
          password: xpxl_dev
        tank:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/tank_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: tank_dev
          password: tank_dev
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/auth_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  #      username: auth_dev
  #      password: auth_dev
  #jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  #snail
  #19980720@Meng
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.snail

access-token-converter:
  signing-key: signingKey
security:
  oauth2:
    login-uri: http://127.0.0.1:8080/server/oauth/token
    client:
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/server/oauth/token_key
        key-value: signingKey
    authorization:
      check-token-access: http://127.0.0.1:8080/server/oauth/check_token

oauth-client-details:
  zero:
    client-id: zero_dev
    client-secret: 123456

wechat:
  zero:
    app-id: wx9cb140f2eacb6870
    app-secret: b873d35be8357186fc8f90c48edb24a9