server:
  port: 8080
  servlet:
    context-path: /server
  address: 0.0.0.0

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: auth
      datasource:
        auth:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:LM8nARWXfZxfoQmjcy3akQ==
          password: mpw:6eP7Qky/AVELy+xz2kLFOQ==
        aili:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/aili_database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:us8Yz3gAAV2wbyNzqcUF1A==
          password: mpw:XNigqMQGjFznlmhk4t1B3A==
        chinaybop:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/chinaybop_database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:PVcp8y7KF6X+mPE7sZcXdg==
          password: mpw:msFF/aonDY+iJF+sPFXa+qzrFDvaJZiZbf8MpfJDYPM=
        king:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/king_database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:aQz+KIBz3H1uWEQXTO0KQg==
          password: mpw:UeO9VpBDcQPcKHNBSA8FUA==
        proxy:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/proxy_database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:xnmTEHzyhjeQyCShzeK/UA==
          password: mpw:meINMh6nA7na6T6XG7t26g==
        xpxl:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/xpxl_database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:5CojpeI3vm3xZYRa8dUbIw==
          password: mpw:IDUWNUuxFodTuUlle+p1Ww==
        tank:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/tank_database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:di3HgvsiCTG/V8mqrA3GGg==
          password: mpw:rDV9/H95uDWtf50KNnToqQ==
        zero:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/zero_cloud?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: mpw:9OUPNSbfHG2SG2TNkTVuOg==
          password: mpw:bwmDC8O96xYWdqEpuZFXMA==
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000

mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.snail

access-token-converter:
  signing-key: signingKey

security:
  oauth2:
    login-uri: http://127.0.0.1:8080/server/oauth/token
    client:
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/server/oauth/token_key
        key-value: signingKey
    authorization:
      check-token-access: http://127.0.0.1:8080/server/oauth/check_token

oauth-client-details:
  zero:
    client-id: zero_dev
    client-secret: 123456

wechat:
  zero:
    app-id: wx9cb140f2eacb6870
    app-secret: b873d35be8357186fc8f90c48edb24a9