server:
  port: 8080
  servlet:
    context-path: /server
  address: 0.0.0.0
spring:
  datasource:
    dynamic:
      primary: auth
      datasource:
        auth:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: snail
          password: 19980720@Meng
        aili:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/zero_cloud_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: zero_cloud_dev
          password: zero_cloud_dev
        chinaybop:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: snail
          password: 19980720@Meng
        king:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: snail
          password: 19980720@Meng
        proxy:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: snail
          password: 19980720@Meng
        xpxl:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: snail
          password: 19980720@Meng
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://ec2-54-223-205-20.cn-north-1.compute.amazonaws.com.cn:3306/auth_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: auth_dev
#      password: auth_dev


