security:
  oauth2:
    client:
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/server/oauth/token_key
        key-value: signingKey
    authorization:
      check-token-access: http://127.0.0.1:8080/server/oauth/check_token

swagger: http://localhost:10000

server:
  port: 10000
  max-http-header-size: 10240000
  servlet:
    context-path: /star
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.164.50:3306/star?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: snail
    password: 19980720@Meng
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.snail