server:
  port: 8080
  servlet:
    context-path: /server
  address: 0.0.0.0
spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: auth
      datasource:
        auth:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-43-192-61-121.cn-northwest-1.compute.amazonaws.com.cn:3306/auth_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&connectTimeout=30000&socketTimeout=60000
          username: yeem_dev
          password: yeem_dev
        proxy:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ec2-43-192-61-121.cn-northwest-1.compute.amazonaws.com.cn:3306/proxy_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&connectTimeout=30000&socketTimeout=60000
          username: yeem_dev
          password: yeem_dev
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 60000
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.yeem

# Oauth2信息
access-token-converter:
  signing-key: signingKey
security:
  oauth2:
    login-uri: http://127.0.0.1:8080/server/oauth/token
    client:
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/server/oauth/token_key
        key-value: signingKey
    authorization:
      check-token-access: http://127.0.0.1:8080/server/oauth/check_token

# Oauth2客户端信息
oauth-client-details:
  zero:
    # 客户端ID
    client-id: zero_dev
    # 客户端密码
    client-secret: 123456

# 微信小程序
wechat:
  zero:
    # appId
    app-id: wx9cb140f2eacb6870
    # appSecret
    app-secret: b873d35be8357186fc8f90c48edb24a9

# 腾讯云COS存储
tencent:
  cos:
    # 桶名称
    bucket-name: ed-fs-1301197907
    # 密钥ID
    secret-id: AKIDb9UbVAcomW1HI5edPyKT4QXQ6XkjY9Vc
    # 密钥Key
    secret-key: 00mJcgV5QWN0OYBdrqeHhtseBTXLtDHA
    # 地区
    region: ap-shanghai